[build]
  command = "pip install -r requirements.txt"
  publish = "frontend"

[functions]
  # Netlify va scanner la racine et trouver main.py
  included_files = ["backend/**", "frontend/**"]

[[redirects]]
  from = "/api/*"
  # ICI : 'main' doit correspondre au nom de ton fichier 'main.py'
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200