[build]
  command = "pip install -r requirements.txt"
  publish = "frontend"

[functions]
  # On pointe vers la racine du projet pour être sûr de tout inclure
  directory = "netlify/functions"
  node_bundler = "esbuild" # Optionnel, aide parfois à la stabilité

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/api/:splat"
  status = 200
  force = true  # On force Netlify à ignorer le HTML pour l'API

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200